---
- hosts: all  
  tasks:
  - name: Add Ansible PPA
    apt_repository:
      repo: 'ppa:ansible/ansible'
    become: true
  - name: Install Packages
    package: name={{item}} state=latest
    with_items:
      - docker.io
      - ansible
      - python-pip
      - docker-py
    become: true
  - name: Install docker.py
    pip:
      name: docker-py
