---
- hosts: all
  pre_tasks: 
    - name: Install dependencies
      - include_tasks: dependencies.yml
  
  tasks:
    - name: Deploy Docker container  
      - include_tasks: heimdall-docker-playbook.yml